/**
 * @frosted-ui/icons adapter (the original frosted-ui icon set, 16px cut).
 * Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/frosted';
 *
 * Or scope it with `<IconProvider library={frostedAdapter}>`.
 *
 * Note: `Folder` and `LogIn` have no @frosted-ui/icons equivalent and are unmapped.
 */
import {
  ArrowDown16,
  ArrowLeft16,
  ArrowRight16,
  ArrowUp16,
  ArrowUpRightFromSquare16,
  Bell16,
  Calendar16,
  Camera16,
  Checkmark16,
  ChevronDown16,
  ChevronLeft16,
  ChevronRight16,
  ChevronUp16,
  Clock16,
  Copy16,
  Document16,
  Download16,
  ExclamationCircle16,
  ExclamationTriangle16,
  Eye16,
  EyeSlashed16,
  FilterDown16,
  Gear16,
  Globe16,
  Heart16,
  Home16,
  InfoCircle16,
  Link16,
  Lock16,
  LockOpen16,
  Logout16,
  MagnifyingGlass16,
  Mail16,
  Menu16,
  Moon16,
  Pause16,
  Pencil16,
  People16,
  Photo16,
  Play16,
  Plus16,
  QuestionCircle16,
  Rotate16,
  Star16,
  Subtract16,
  Sun16,
  Telephone16,
  ThreeDotsHorizontal16,
  ThreeDotsVertical16,
  Trash16,
  Upload16,
  User16,
  XMark16,
} from '@frosted-ui/icons';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const frostedAdapter: IconAdapter = {
  name: 'frosted',
  icons: {
    AlertCircle: ExclamationCircle16,
    ArrowDown: ArrowDown16,
    ArrowLeft: ArrowLeft16,
    ArrowRight: ArrowRight16,
    ArrowUp: ArrowUp16,
    Bell: Bell16,
    Calendar: Calendar16,
    Camera: Camera16,
    Check: Checkmark16,
    ChevronDown: ChevronDown16,
    ChevronLeft: ChevronLeft16,
    ChevronRight: ChevronRight16,
    ChevronUp: ChevronUp16,
    Clock: Clock16,
    Close: XMark16,
    Copy: Copy16,
    DotsHorizontal: ThreeDotsHorizontal16,
    DotsVertical: ThreeDotsVertical16,
    Download: Download16,
    Edit: Pencil16,
    ExternalLink: ArrowUpRightFromSquare16,
    Eye: Eye16,
    EyeOff: EyeSlashed16,
    File: Document16,
    Filter: FilterDown16,
    Globe: Globe16,
    Heart: Heart16,
    HelpCircle: QuestionCircle16,
    Home: Home16,
    Image: Photo16,
    Info: InfoCircle16,
    Link: Link16,
    Lock: Lock16,
    LogOut: Logout16,
    Mail: Mail16,
    Menu: Menu16,
    Minus: Subtract16,
    Moon: Moon16,
    Pause: Pause16,
    Phone: Telephone16,
    Play: Play16,
    Plus: Plus16,
    Refresh: Rotate16,
    Search: MagnifyingGlass16,
    Settings: Gear16,
    Star: Star16,
    Sun: Sun16,
    Trash: Trash16,
    Unlock: LockOpen16,
    Upload: Upload16,
    User: User16,
    Users: People16,
    Warning: ExclamationTriangle16,
  },
};

registerIconAdapter(frostedAdapter);
