/**
 * @frosted-ui/icons (the original frosted-ui icon set, 16px cut) adapter. Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/frosted';
 *
 * Or scope it with `<IconProvider library={frostedAdapter}>`.
 *
 * The following canonical names have no @frosted-ui/icons equivalent and are unmapped:
 *   `Archive`, `AtSign`, `Battery`, `Bookmark`, `Bug`, `Cloud`, `Database`, `Folder`, `Key`, `LogIn`,
 *   `Package`, `Paperclip`, `Printer`, `Scissors`, `Send`, `Server`, `ShoppingCart`, `Sliders`,
 *   `Terminal`, `Video`, `VolumeOff`, `Wifi`.
 *
 * GENERATED FILE — do not edit by hand. Edit `scripts/icon-map.ts` and run
 * `bun run generate:icon-adapters`.
 */
import {
  ArrowDown16,
  ArrowLeft16,
  ArrowRight16,
  ArrowUp16,
  ArrowUpRightFromSquare16,
  Bell16,
  Bolt16,
  Brush16,
  Calendar16,
  Camera16,
  Checkmark16,
  ChevronDown16,
  ChevronLeft16,
  ChevronRight16,
  ChevronUp16,
  Clock16,
  Code16,
  Copy16,
  CreditCard16,
  Document16,
  Download16,
  ExclamationCircle16,
  ExclamationTriangle16,
  Eye16,
  EyeSlashed16,
  FilterDown16,
  Fire16,
  Flag16,
  Gear16,
  Gift16,
  Globe16,
  Grid16,
  Happy16,
  Hashtag16,
  Heart16,
  Home16,
  Inbox16,
  InfoCircle16,
  Link16,
  ListBullet16,
  LocationPin16,
  Lock16,
  LockOpen16,
  Logout16,
  MagnifyingGlass16,
  Mail16,
  Menu16,
  Message16,
  Microphone16,
  Moon16,
  Palette16,
  Pause16,
  Pencil16,
  People16,
  Photo16,
  Play16,
  Plus16,
  QuestionCircle16,
  Rotate16,
  ShareNodes16,
  Shield16,
  Speaker16,
  Star16,
  Subtract16,
  Sun16,
  Tag16,
  Telephone16,
  ThreeDotsHorizontal16,
  ThreeDotsVertical16,
  ThumbDown16,
  ThumbUp16,
  Trash16,
  Trophy16,
  Truck16,
  Upload16,
  User16,
  XMark16,
} from '@frosted-ui/icons';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const frostedAdapter: IconAdapter = {
  name: 'frosted',
  icons: {
    AlertCircle: ExclamationCircle16,
    ArrowDown: ArrowDown16,
    ArrowLeft: ArrowLeft16,
    ArrowRight: ArrowRight16,
    ArrowUp: ArrowUp16,
    Bell: Bell16,
    Brush: Brush16,
    Calendar: Calendar16,
    Camera: Camera16,
    Check: Checkmark16,
    ChevronDown: ChevronDown16,
    ChevronLeft: ChevronLeft16,
    ChevronRight: ChevronRight16,
    ChevronUp: ChevronUp16,
    Clock: Clock16,
    Close: XMark16,
    Code: Code16,
    Copy: Copy16,
    CreditCard: CreditCard16,
    DotsHorizontal: ThreeDotsHorizontal16,
    DotsVertical: ThreeDotsVertical16,
    Download: Download16,
    Edit: Pencil16,
    ExternalLink: ArrowUpRightFromSquare16,
    Eye: Eye16,
    EyeOff: EyeSlashed16,
    File: Document16,
    Filter: FilterDown16,
    Flag: Flag16,
    Flame: Fire16,
    Gift: Gift16,
    Globe: Globe16,
    Hash: Hashtag16,
    Heart: Heart16,
    HelpCircle: QuestionCircle16,
    Home: Home16,
    Image: Photo16,
    Inbox: Inbox16,
    Info: InfoCircle16,
    LayoutGrid: Grid16,
    Link: Link16,
    List: ListBullet16,
    Lock: Lock16,
    LogOut: Logout16,
    Mail: Mail16,
    MapPin: LocationPin16,
    Menu: Menu16,
    Message: Message16,
    Mic: Microphone16,
    Minus: Subtract16,
    Moon: Moon16,
    Palette: Palette16,
    Pause: Pause16,
    Phone: Telephone16,
    Play: Play16,
    Plus: Plus16,
    Refresh: Rotate16,
    Search: MagnifyingGlass16,
    Settings: Gear16,
    Share: ShareNodes16,
    Shield: Shield16,
    Smile: Happy16,
    Star: Star16,
    Sun: Sun16,
    Tag: Tag16,
    ThumbsDown: ThumbDown16,
    ThumbsUp: ThumbUp16,
    Trash: Trash16,
    Trophy: Trophy16,
    Truck: Truck16,
    Unlock: LockOpen16,
    Upload: Upload16,
    User: User16,
    Users: People16,
    Volume: Speaker16,
    Warning: ExclamationTriangle16,
    Zap: Bolt16,
  },
};

registerIconAdapter(frostedAdapter);
