/**
 * @heroicons/react adapter (24px outline set). Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/heroicons';
 *
 * Or scope it with `<IconProvider library={heroiconsAdapter}>`.
 */
import {
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  Bars3Icon,
  BellIcon,
  CalendarIcon,
  CameraIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  Cog6ToothIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  FunnelIcon,
  GlobeAltIcon,
  HeartIcon,
  HomeIcon,
  InformationCircleIcon,
  LinkIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  PauseIcon,
  PencilIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  StarIcon,
  SunIcon,
  TrashIcon,
  UserIcon,
  UsersIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const heroiconsAdapter: IconAdapter = {
  name: 'heroicons',
  icons: {
    AlertCircle: ExclamationCircleIcon,
    ArrowDown: ArrowDownIcon,
    ArrowLeft: ArrowLeftIcon,
    ArrowRight: ArrowRightIcon,
    ArrowUp: ArrowUpIcon,
    Bell: BellIcon,
    Calendar: CalendarIcon,
    Camera: CameraIcon,
    Check: CheckIcon,
    ChevronDown: ChevronDownIcon,
    ChevronLeft: ChevronLeftIcon,
    ChevronRight: ChevronRightIcon,
    ChevronUp: ChevronUpIcon,
    Clock: ClockIcon,
    Close: XMarkIcon,
    Copy: DocumentDuplicateIcon,
    DotsHorizontal: EllipsisHorizontalIcon,
    DotsVertical: EllipsisVerticalIcon,
    Download: ArrowDownTrayIcon,
    Edit: PencilIcon,
    ExternalLink: ArrowTopRightOnSquareIcon,
    Eye: EyeIcon,
    EyeOff: EyeSlashIcon,
    File: DocumentIcon,
    Filter: FunnelIcon,
    Folder: FolderIcon,
    Globe: GlobeAltIcon,
    Heart: HeartIcon,
    HelpCircle: QuestionMarkCircleIcon,
    Home: HomeIcon,
    Image: PhotoIcon,
    Info: InformationCircleIcon,
    Link: LinkIcon,
    Lock: LockClosedIcon,
    LogIn: ArrowLeftEndOnRectangleIcon,
    LogOut: ArrowRightStartOnRectangleIcon,
    Mail: EnvelopeIcon,
    Menu: Bars3Icon,
    Minus: MinusIcon,
    Moon: MoonIcon,
    Pause: PauseIcon,
    Phone: PhoneIcon,
    Play: PlayIcon,
    Plus: PlusIcon,
    Refresh: ArrowPathIcon,
    Search: MagnifyingGlassIcon,
    Settings: Cog6ToothIcon,
    Star: StarIcon,
    Sun: SunIcon,
    Trash: TrashIcon,
    Unlock: LockOpenIcon,
    Upload: ArrowUpTrayIcon,
    User: UserIcon,
    Users: UsersIcon,
    Warning: ExclamationTriangleIcon,
  },
};

registerIconAdapter(heroiconsAdapter);
