/**
 * lucide-react adapter. Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/lucide';
 *
 * Or scope it with `<IconProvider library={lucideAdapter}>`.
 */
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleQuestionMark,
  Clock,
  Copy,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Folder,
  Funnel,
  Globe,
  Heart,
  House,
  Image,
  Info,
  Link,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  X,
} from 'lucide-react';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const lucideAdapter: IconAdapter = {
  name: 'lucide',
  icons: {
    AlertCircle: CircleAlert,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bell,
    Calendar,
    Camera,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clock,
    Close: X,
    Copy,
    DotsHorizontal: Ellipsis,
    DotsVertical: EllipsisVertical,
    Download,
    Edit: Pencil,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    Filter: Funnel,
    Folder,
    Globe,
    Heart,
    HelpCircle: CircleQuestionMark,
    Home: House,
    Image,
    Info,
    Link,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Menu,
    Minus,
    Moon,
    Pause,
    Phone,
    Play,
    Plus,
    Refresh: RefreshCw,
    Search,
    Settings,
    Star,
    Sun,
    Trash: Trash2,
    Unlock: LockOpen,
    Upload,
    User,
    Users,
    Warning: TriangleAlert,
  },
};

registerIconAdapter(lucideAdapter);
