/**
 * @phosphor-icons/react adapter. Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/phosphor';
 *
 * Or scope it with `<IconProvider library={phosphorAdapter}>`.
 */
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  Bell,
  Calendar,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  Clock,
  Copy,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  Eye,
  EyeSlash,
  File,
  Folder,
  Funnel,
  Gear,
  Globe,
  Heart,
  House,
  Image,
  Info,
  Link,
  List,
  Lock,
  LockOpen,
  MagnifyingGlass,
  Minus,
  Moon,
  Pause,
  PencilSimple,
  Phone,
  Play,
  Plus,
  Question,
  SignIn,
  SignOut,
  Star,
  Sun,
  Trash,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  X,
} from '@phosphor-icons/react';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const phosphorAdapter: IconAdapter = {
  name: 'phosphor',
  icons: {
    AlertCircle: WarningCircle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bell,
    Calendar,
    Camera,
    Check,
    ChevronDown: CaretDown,
    ChevronLeft: CaretLeft,
    ChevronRight: CaretRight,
    ChevronUp: CaretUp,
    Clock,
    Close: X,
    Copy,
    DotsHorizontal: DotsThree,
    DotsVertical: DotsThreeVertical,
    Download: DownloadSimple,
    Edit: PencilSimple,
    ExternalLink: ArrowSquareOut,
    Eye,
    EyeOff: EyeSlash,
    File,
    Filter: Funnel,
    Folder,
    Globe,
    Heart,
    HelpCircle: Question,
    Home: House,
    Image,
    Info,
    Link,
    Lock,
    LogIn: SignIn,
    LogOut: SignOut,
    Mail: Envelope,
    Menu: List,
    Minus,
    Moon,
    Pause,
    Phone,
    Play,
    Plus,
    Refresh: ArrowsClockwise,
    Search: MagnifyingGlass,
    Settings: Gear,
    Star,
    Sun,
    Trash,
    Unlock: LockOpen,
    Upload: UploadSimple,
    User,
    Users,
    Warning,
  },
};

registerIconAdapter(phosphorAdapter);
