/**
 * @tabler/icons-react adapter. Importing this module registers it:
 *
 *   import '@aussieljk/frosted/icons/tabler';
 *
 * Or scope it with `<IconProvider library={tablerAdapter}>`.
 */
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconCalendar,
  IconCamera,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconCopy,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFilter,
  IconFolder,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconInfoCircle,
  IconLink,
  IconLock,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMinus,
  IconMoon,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconStar,
  IconSun,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconWorld,
  IconX,
} from '@tabler/icons-react';
import { registerIconAdapter } from '../registry';
import type { IconAdapter } from '../types';

export const tablerAdapter: IconAdapter = {
  name: 'tabler',
  icons: {
    AlertCircle: IconAlertCircle,
    ArrowDown: IconArrowDown,
    ArrowLeft: IconArrowLeft,
    ArrowRight: IconArrowRight,
    ArrowUp: IconArrowUp,
    Bell: IconBell,
    Calendar: IconCalendar,
    Camera: IconCamera,
    Check: IconCheck,
    ChevronDown: IconChevronDown,
    ChevronLeft: IconChevronLeft,
    ChevronRight: IconChevronRight,
    ChevronUp: IconChevronUp,
    Clock: IconClock,
    Close: IconX,
    Copy: IconCopy,
    DotsHorizontal: IconDots,
    DotsVertical: IconDotsVertical,
    Download: IconDownload,
    Edit: IconPencil,
    ExternalLink: IconExternalLink,
    Eye: IconEye,
    EyeOff: IconEyeOff,
    File: IconFile,
    Filter: IconFilter,
    Folder: IconFolder,
    Globe: IconWorld,
    Heart: IconHeart,
    HelpCircle: IconHelpCircle,
    Home: IconHome,
    Image: IconPhoto,
    Info: IconInfoCircle,
    Link: IconLink,
    Lock: IconLock,
    LogIn: IconLogin,
    LogOut: IconLogout,
    Mail: IconMail,
    Menu: IconMenu2,
    Minus: IconMinus,
    Moon: IconMoon,
    Pause: IconPlayerPause,
    Phone: IconPhone,
    Play: IconPlayerPlay,
    Plus: IconPlus,
    Refresh: IconRefresh,
    Search: IconSearch,
    Settings: IconSettings,
    Star: IconStar,
    Sun: IconSun,
    Trash: IconTrash,
    Unlock: IconLockOpen,
    Upload: IconUpload,
    User: IconUser,
    Users: IconUsers,
    Warning: IconAlertTriangle,
  },
};

registerIconAdapter(tablerAdapter);
