/**
 * Generates src/styles/tokens/tailwind-color.css: every Tailwind CSS v4 palette
 * mapped onto frosted-ui's 12-step Radix-style scales (light + dark + alpha),
 * exposed under `tw-` prefixed names (`tw-red`, `tw-slate`, ...).
 *
 * Source of truth is tailwindcss/theme.css (the oklch palette definitions).
 *
 * Run with: bun scripts/generate-tailwind-colors.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tailwindColorScales, tailwindGrayScales } from '../src/helpers/tailwind-colors';
import { createPaletteCss, tailwindPaletteStops, type TailwindPalette } from '../src/helpers/tailwind-palette';

const require = createRequire(import.meta.url);
const themeCssPath = require.resolve('tailwindcss/theme.css');
const themeCss = readFileSync(themeCssPath, 'utf8');

// Collect --color-{name}-{stop}: <value>; declarations from tailwindcss/theme.css.
const palettes = new Map<string, Partial<Record<number, string>>>();
for (const match of themeCss.matchAll(/--color-([a-z]+)-(\d+):\s*([^;]+);/g)) {
  const [, name, stop, value] = match;
  const palette = palettes.get(name) ?? {};
  palette[Number(stop)] = value.trim();
  palettes.set(name, palette);
}

const sections: string[] = [];
for (const scaleName of tailwindColorScales) {
  const baseName = scaleName.slice('tw-'.length);
  const palette = palettes.get(baseName);
  if (!palette) throw new Error(`Palette "${baseName}" not found in ${themeCssPath}`);
  for (const stop of tailwindPaletteStops) {
    if (!palette[stop]) throw new Error(`Palette "${baseName}" is missing stop ${stop}`);
  }

  const isGray = (tailwindGrayScales as readonly string[]).includes(scaleName);
  sections.push(`/* ${scaleName} */\n${createPaletteCss(scaleName, palette as TailwindPalette, { gray: isGray })}`);
}

const header = `/*
 * Generated by scripts/generate-tailwind-colors.ts — do not edit by hand.
 * Regenerate with: bun scripts/generate-tailwind-colors.ts
 *
 * Tailwind CSS v4 palettes mapped onto frosted-ui's 12-step Radix-style scales.
 */

`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), '../src/styles/tokens/tailwind-color.css');
writeFileSync(outPath, header + sections.join('\n'));
console.log(`Wrote ${outPath} (${tailwindColorScales.length} palettes)`);
